export const SET_CURRENT_USER = 'SET_CURRENT_USER'

// google sign in
export const GOOGLE_SIGNIN_START = 'GOOGLE_SIGNIN_START'
export const GOOGLE_SIGNIN_SUCCESS = 'GOOGLE_SIGNIN_SUCCESS'
export const GOOGLE_SIGNIN_FAILURE = 'GOOGLE_SIGNIN_FAILURE'

// email & password sign in
export const EMAIL_SIGNIN_START = 'EMAIL_SIGNIN_START'
export const EMAIL_SIGNIN_SUCCESS = 'EMAIL_SIGNIN_SUCCESS'
export const EMAIL_SIGNIN_FAILURE = 'GOOGLE_SIGNIN_FAILURE'
