export const SET_CURRENT_USER = 'SET_CURRENT_USER'

// Sign in
export const GOOGLE_SIGNIN_START = 'GOOGLE_SIGNIN_START'
export const EMAIL_SIGNIN_START = 'EMAIL_SIGNIN_START'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

// check user session
export const CHECK_USER_SESSION = 'CHECK_USER_SESSION'
